apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-tkju
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0072-tenant/tkrw-pr712-0075-0072-app/devfile-sample-tkju@sha256:25a0b47385d2e8ab983f52dc0b3b91ce59c941b7fe7d091765f4318d30d7d305
        name: my-nodejs
        resources: {}
status: {}
